<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_BannerSlider
 */
?>
<?php
/** @var Amasty\BannerSlider\Block\Widget\Slider $block */
$slider = $block->getSlider();
?>

<?php if ($slider && count($block->getBanners())): ?>
    <div class="ambanner-slider-wrap" data-ambanner-js="slider-wrapper">
        <?php if ($block->getData('show_name')): ?>
            <h2 class="ambanner-title">
                <?= $block->escapeHtml($slider->getName()) ?>
            </h2>
        <?php endif; ?>
        <div class="ambanner-slider-block <?= $block->escapeHtmlAttr($block->getSliderClass()) ?>"
             data-ambanner-js="slider"
             data-mage-init='{"amSlider":{
                 "sliderBlockWidth": <?= $block->escapeJs($slider->getBannerWidth()) ?>,
                 "sliderAnimationEffect": <?= $block->escapeJs($slider->getAnimationEffect()) ?>,
                 "transitionSpeed": <?= $block->escapeJs($slider->getTransitionSpeed()) ?>,
                 "isAutoplay": <?= /* @noEscape */ $slider->getAutoplay() ? 'true' : 'false' ?>,
                 "sliderOptions": {
                     "arrows": <?= /* @noEscape */ $slider->getNavigationArrows() ? 'true' : 'false' ?>,
                     "dots": <?= /* @noEscape */ $slider->getNavigationBullets() ? 'true' : 'false' ?>,
                     "autoplay": <?= /* @noEscape */ $slider->getAutoplay() ? 'true' : 'false' ?>,
                     "autoplaySpeed": <?= $block->escapeJs($slider->getPauseTime()) ?>,
                     "speed": <?= $block->escapeJs($slider->getTransitionSpeed()) ?>,
                     "responsive": [{
                         "breakpoint": 768,
                         "settings": {
                             <?php if ($slider->getNavigationArrows()): ?>
                             "arrows": <?= /* @noEscape */ $slider->getNavigationBullets() ? 'false' : 'true' ?>,
                             <?php endif; ?>
                             "dots": <?= /* @noEscape */ $slider->getNavigationBullets() ? 'true' : 'false' ?>
                         }
                     }]
                 }
             }}'
        >
            <?php foreach ($block->getBanners() as $banner): ?>
                <div class="ambanner-item-block" data-ambanner-js="item">
                    <div class="ambanner-image-block <?= /* @noEscape */ $banner->getHoverText() ? '-overlay' : '' ?>">
                        <img src="<?= $block->escapeUrl($block->getImageSrc($banner)) ?>"
                             alt="<?= $block->escapeHtmlAttr($banner->getImageAlt()) ?>"
                             class="ambanner-image"
                        />
                    </div>
                    <?php if ($banner->getHoverText()): ?>
                        <button class="ambanner-button -show-overlay ambanner-icon -show-more"
                                data-ambanner-js="show-more"
                                title="<?= $block->escapeHtmlAttr(__('Show content')) ?>"
                                aria-label="<?= $block->escapeHtmlAttr(__('Show content')) ?>"
                        >
                            <?= $block->escapeHtml(__('Show content')) ?>
                        </button>
                        <div class="ambanner-content-overlay">
                            <span class="ambanner-overlay-circle" data-ambanner-js="overlay"></span>
                            <div class="ambanner-content-block">
                                <?= /* @noEscape */ $banner->getHoverText() ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php if ($banner->getTargetUrl()): ?>
                        <a class="ambanner-link" target="_blank"
                           title="<?= $block->escapeHtmlAttr($banner->getImageAlt()) ?>"
                           href="<?= $block->escapeUrl($banner->getTargetUrl()) ?>"></a>
                    <?php endif; ?>
                </div>
            <?php endforeach ?>
        </div>
    </div>
<?php endif; ?>
